# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb5f7a2757ae09ca09b5a82765bb35a3de7e6b65b6f403403accf69de11c024717fa4716651fff8a40fca48abd7f9d06ccb5cd87cd4e2f56a6319aad362cb3fc

test:
  secret_key_base: 81adb819573531fc1601e4673b82b9ede63b64e236eafaf106525fe43ae235873d7f7981077295f2e329f08ae8ed8b34dee4abbe4b3d17c3d6f3b71d49bee2f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
